name: Docker Image from pull request

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_HEAD_REF##*/}
    - name: Build the Docker images
      run: |
        export GITHUB_TAG_NAME=${GITHUB_HEAD_REF##*/}
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make docker-image
        make docker-push
